Repository dejan-xd-organization/NistagramFrontend, pull requests merged in 2021-08, with the labels that each got.

#6 Close #3
  .github/workflows/CI.yml
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/headers/headers.component.ts
  src/app/components/offline/login/login.component.html
  src/app/components/offline/login/login.component.spec.ts
  src/app/components/offline/login/login.component.ts
  src/app/components/online/home-online/home-online.component.html
  src/app/components/online/home-online/home-online.component.ts
  src/app/guard/not-auth.guard.spec.ts
  src/app/guard/not-auth.guard.ts
  src/app/services/offline-home.service.ts
  src/assets/css/style.css
  src/assets/js/script.js
Labels: user story

#7 Close #2
  .github/workflows/CI.yml
  src/app/components/offline/login/login.component.html
  src/app/components/offline/login/login.component.spec.ts
  src/app/components/offline/registration/registration.component.html
  src/app/components/offline/registration/registration.component.spec.ts
  src/app/components/offline/registration/registration.component.ts
  src/app/services/offline-home.service.ts
Labels: user story

#16 create_link_posts -> develop Close #9
  src/app/components/offline/home/home.component.spec.ts
  src/app/components/offline/home/home.component.ts
  src/app/services/offline-home.service.ts
Labels: bug, enhancement, pull request

#17 filter_page -> develop Close #10
  src/app/components/headers/headers.component.css
  src/app/components/headers/headers.component.html
  src/app/components/headers/headers.component.spec.ts
  src/app/components/headers/headers.component.ts
  src/app/services/offline-home.service.ts
Labels: user story, pull request

#18 sonar_cloud -> develop Close #11
  src/app/components/offline/list-new-people/list-new-people.component.html
  src/app/global/global.ts
  src/app/guard/not-auth.guard.ts
  src/app/services/authenticate.service.spec.ts
  src/app/services/offline-home.service.ts
  src/app/services/online-home.service.ts
Labels: bug, documentation, pull request

#19 develop -> master Sprint 2 Release v1.0.1
  .github/workflows/CI.yml
  src/app/components/headers/headers.component.css
  src/app/components/headers/headers.component.html
  src/app/components/headers/headers.component.spec.ts
  src/app/components/headers/headers.component.ts
  src/app/components/offline/home/home.component.spec.ts
  src/app/components/offline/home/home.component.ts
  src/app/components/offline/list-new-people/list-new-people.component.html
  src/app/components/offline/login/login.component.spec.ts
  src/app/components/offline/login/login.component.ts
  src/app/components/offline/registration/registration.component.spec.ts
  src/app/components/offline/registration/registration.component.ts
  src/app/components/online/home-online/home-online.component.spec.ts
  src/app/global/global.ts
  src/app/guard/not-auth.guard.ts
  src/app/services/authenticate.service.spec.ts
  src/app/services/offline-home.service.spec.ts
  src/app/services/offline-home.service.ts
  src/app/services/online-home.service.ts
  src/assets/images/resources/user-avatar-default.png
Labels: user story, release, pull request

#26 edit_user_page -> develop Close #25
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/headers/headers.component.html
  src/app/components/online/home-online/home-online.component.html
  src/app/components/online/home-online/home-online.component.spec.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.css
  src/app/components/online/profile/edit-profile/edit-profile.component.html
  src/app/components/online/profile/edit-profile/edit-profile.component.spec.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.ts
  src/app/components/online/profile/view-profile/view-profile.component.html
  src/app/components/online/profile/view-profile/view-profile.component.spec.ts
  src/app/components/online/profile/view-profile/view-profile.component.ts
  src/app/guard/auth.guard.ts
  src/app/services/online-home.service.ts
Labels: user story, pull request

#27 view_page -> develop Close #21, Close #22
  src/app/components/headers/headers.component.html
  src/app/components/offline/login/login.component.css
  src/app/components/offline/login/login.component.html
  src/app/components/offline/login/login.component.ts
  src/app/components/offline/registration/registration.component.css
  src/app/components/offline/registration/registration.component.html
  src/app/components/offline/registration/registration.component.ts
  src/app/components/online/home-online/home-online.component.css
  src/app/components/online/home-online/home-online.component.html
  src/app/components/online/home-online/home-online.component.spec.ts
  src/app/components/online/home-online/home-online.component.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.html
  src/app/components/online/profile/edit-profile/edit-profile.component.ts
  src/app/components/online/profile/view-profile/view-profile.component.css
  src/app/components/online/profile/view-profile/view-profile.component.html
  src/app/components/online/profile/view-profile/view-profile.component.ts
  src/app/services/offline-home.service.spec.ts
  src/app/services/offline-home.service.ts
  src/app/services/online-home.service.ts
Labels: user story, pull request

#28 sonar_cloud -> develop Bug/sonar cloud
  src/app/app-routing.module.ts
  src/app/components/headers/headers.component.html
  src/app/components/online/home-online/home-online.component.html
  src/app/components/online/home-online/home-online.component.spec.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.html
  src/app/components/online/profile/edit-profile/edit-profile.component.spec.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.ts
  src/app/components/online/profile/view-profile/view-profile.component.html
  src/app/components/online/profile/view-profile/view-profile.component.spec.ts
  src/app/components/online/profile/view-profile/view-profile.component.ts
  src/app/guard/auth.guard.ts
  src/app/services/authenticate.service.spec.ts
  src/app/services/offline-home.service.ts
  src/app/services/online-home.service.ts
Labels: bug, documentation, user story

#29 develop -> master Sprint 3 Release v1.0.2
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/headers/headers.component.html
  src/app/components/offline/all-post/all-post.component.html
  src/app/components/offline/list-new-people/list-new-people.component.html
  src/app/components/offline/login/login.component.css
  src/app/components/offline/login/login.component.html
  src/app/components/offline/login/login.component.ts
  src/app/components/offline/registration/registration.component.css
  src/app/components/offline/registration/registration.component.html
  src/app/components/offline/registration/registration.component.ts
  src/app/components/online/home-online/home-online.component.css
  src/app/components/online/home-online/home-online.component.html
  src/app/components/online/home-online/home-online.component.spec.ts
  src/app/components/online/home-online/home-online.component.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.css
  src/app/components/online/profile/edit-profile/edit-profile.component.html
  src/app/components/online/profile/edit-profile/edit-profile.component.spec.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.ts
  src/app/components/online/profile/view-profile/view-profile.component.css
  src/app/components/online/profile/view-profile/view-profile.component.html
  src/app/components/online/profile/view-profile/view-profile.component.spec.ts
  src/app/components/online/profile/view-profile/view-profile.component.ts
  src/app/guard/auth.guard.ts
  src/app/services/authenticate.service.spec.ts
  src/app/services/offline-home.service.spec.ts
  src/app/services/offline-home.service.ts
  src/app/services/online-home.service.spec.ts
  src/app/services/online-home.service.ts
  src/assets/images/nistagram-logo.png
Labels: user story, release, pull request

#31 feature/chat -> develop Feature/chat
  src/app/app-routing.module.ts
  src/app/components/headers/headers.component.html
  src/app/components/headers/headers.component.ts
  src/app/components/offline/all-post/all-post.component.html
  src/app/components/offline/list-new-people/list-new-people.component.html
  src/app/components/online/home-online/home-online.component.html
  src/app/components/online/messages/messages.component.html
  src/app/components/online/messages/messages.component.spec.ts
  src/app/components/online/messages/messages.component.ts
  src/app/components/online/profile/edit-profile/edit-profile.component.html
  src/app/components/online/profile/view-profile/view-profile.component.html
  src/app/components/online/profile/view-profile/view-profile.component.spec.ts
  src/app/components/online/profile/view-profile/view-profile.component.ts
  src/app/services/online-home.service.ts
Labels: user story, pull request
